---
title: "Short Report 2 Code"
author: "Anna Ursin and Kunwu Lyu"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = T, error=FALSE, message=FALSE, warning=FALSE)
library(tidyverse)
library(ggplot2)
library(GGally)
library(ggResidpanel)
library(broom)
library(patchwork)
library(purrr)
library(car)
library(corrplot)
library(MASS)
```

## Data Wrangling
```{r}
#Variable Distributions through Histograms
hist(wine_dat$residual.sugar, main = "Distribution of Residual Sugar", xlab = "Residual Sugar")
hist(wine_dat$alcohol, main = "Distribution of Alcohol", xlab = "Alcohol")
hist(wine_dat$pH, main = "Distribution of pH", xlab = "pH")
hist(wine_dat$sulphates, main = "Distribution of Sulphates", xlab = "Sulphates")
```
```{r}
#Variable Distributions through Boxplots
boxplot(wine_dat$residual.sugar, main = "Residual Sugar", ylab = "Residual Sugar")
boxplot(wine_dat$alcohol, main = "Alcohol", ylab = "Alcohol")
boxplot(wine_dat$pH, main = "pH", ylab = "pH")
boxplot(wine_dat$sulphates, main = "Sulphates", ylab = "Sulphates")

```



```{r Read and Scat. Mtrx, cache=TRUE}
## Data Wrangling & Scatterplot Matrix
wine_dat <- read.csv("https://www.math.carleton.edu/ckelling/data/wine_project.csv")
glimpse(wine_dat)
ggpairs(wine_dat) # for all
ggpairs(data = wine_dat, columns = 
          c("alcohol", "sulphates", "pH", 
            "residual.sugar", "quality")) # for interested vars

## dist of quality scores
ggplot(wine_dat, aes(x = quality)) + 
  geom_bar() + 
  facet_grid(cols = vars(color))
  labs(title = "Distribution of Wine Quality Scores")
```


## EDA Plot
```{r Scat. Plot by Clr, cache=TRUE}
## scatterplots for predictors vs wine quality
create_plot <- function(var_name) {
  ggplot(data = wine_dat, 
         aes_string(x = var_name, y = "quality", color = "color")) +
    geom_point(alpha = 0.1, position = position_jitter()) +
    geom_smooth(method = "lm", se = FALSE) + 
    labs(title = paste("Quality vs", var_name))
}

variable_names <- c("alcohol", "sulphates", "pH", "residual.sugar")
plot_list <- map(variable_names, create_plot)

plot_grid <- wrap_plots(plot_list, ncol = 2)
plot_grid


## scat plot for report
ggplot(data = wine_dat, aes(x = pH, y = quality, color = color)) +
  geom_point(alpha = 0.3, position = position_jitter()) + 
  geom_smooth(method = "lm", se = F) + 
  labs(title = "Quality vs pH, by Color", x = "pH", y = "Quality")


## correlation matrix
wine_numeric <- wine_dat %>% dplyr::select(-color)

corr_matrix <- cor(wine_numeric, use = "complete.obs")
corrplot(corr_matrix, method = "color")
```


## Regression Model
```{r Main Effects and Interaction Model, cache=TRUE}
## Main Effects Model
wine_lm_base <- lm(quality ~ alcohol + sulphates + residual.sugar + pH, data = wine_dat)
summary(wine_lm_base)

## Interaction Model
wine_lm_interaction <- lm(quality ~ alcohol + sulphates + residual.sugar + pH*color, 
                          data = wine_dat)
summary(wine_lm_interaction)
```

### Residual Plots
```{r Interaction Residuals, cache=TRUE}
## Residual Plots with ggResidPanel
resid_panel(wine_lm_interaction, plots = c("hist", "qq", "resid"), smoother = T)
resid_panel(wine_lm_interaction, plots = "resid", smoother = TRUE)
resid_xpanel(wine_lm_interaction, smoother = TRUE)

## Function to create residual plots
create_res_plot <- function(data) {
  # augment data for plotting
  wine_lm_aug <- augment(data, newdata = wine_dat)
  
  #determine if it's transfomred model
  if (identical(data, wine_lm_interaction)) {
    wine_lm_aug$var_sul <- wine_lm_aug$sulphates
    wine_lm_aug$var_sug <- wine_lm_aug$residual.sugar
    sul_name <- "Sulphates"
    sug_name <- "Residual Sugar"
  } else {
    wine_lm_aug$var_sul <- log(wine_lm_aug$sulphates)
    wine_lm_aug$var_sug <- log(wine_lm_aug$residual.sugar)
    sul_name <- "Log(Sulphates)"
    sug_name <- "Log(Residual Sugar)"
  }
  # residual plot
  wine_lm_res1 <- ggplot(wine_lm_aug, aes(x = alcohol, y = .resid)) + 
    geom_point(alpha = 0.3) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
    geom_smooth(method = "loess", color = "red") +
    labs(x = "Alcohol Content", y = "residuals")
  
  wine_lm_res2 <- ggplot(wine_lm_aug, aes(x = var_sul, y = .resid)) + 
    geom_point(alpha = 0.3) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
    geom_smooth(method = "loess", color = "red") +
    labs(x = sul_name, y = "residuals")
  
  wine_lm_res3 <- ggplot(wine_lm_aug, aes(x = var_sug, y = .resid)) + 
    geom_point(alpha = 0.3) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
    geom_smooth(method = "loess", color = "red") +
    labs(x = sug_name, y = "residuals")
  
  wine_lm_res4 <- ggplot(wine_lm_aug, aes(x = pH, y = .resid)) + 
    geom_point(alpha = 0.3) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
    geom_smooth(method = "loess", color = "red") +
    labs(x = "pH Levels", y = "residuals")
  
  wine_lm_res5 <- ggplot(wine_lm_aug, aes(x = color, y = .resid)) + 
    geom_boxplot() +
    geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
    labs(x = "Wine Color", y = "residuals")
  
  wine_lm_res6 <- ggplot(wine_lm_aug, aes(x = .fitted, y = .resid)) + 
    geom_point(alpha = 0.3) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
    geom_smooth(method = "loess", color = "red") + 
    labs(x = "Fitted Values", y = "residuals")
  
  # normal qq plot
  wine_lm_qq <- ggplot(wine_lm_aug, aes(sample = .resid))+
    geom_qq() +
    geom_qq_line(color = "blue") +
    labs(y = "Sample Quantiles", x = "Normal Quantiles")
  
  combined_plot <- (wine_lm_res1 | wine_lm_res2 | wine_lm_res3) / 
    (wine_lm_res4 | wine_lm_res5 | wine_lm_res6) / wine_lm_qq
  combined_plot + 
    plot_layout(guides = 'collect') + 
    plot_annotation(title = "Residual Plot and Normal Q-Q Plot of Wine Quality MLR")
}

# Residual Plot for non-transfomred model
create_res_plot(wine_lm_interaction)

# Selected Residual Plots for report
wine_lm_aug <- augment(wine_lm_interaction, newdata = wine_dat)
wine_lm_res2 <- ggplot(wine_lm_aug, aes(x = sulphates, y = .resid)) + 
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
  geom_smooth(method = "loess", color = "red") +
  labs(x = "Sulphates", y = "residuals")
wine_lm_res3 <- ggplot(wine_lm_aug, aes(x = residual.sugar, y = .resid)) + 
  geom_point(alpha = 0.3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "blue") + 
  geom_smooth(method = "loess", color = "red") +
  labs(x = "Residual Sugar", y = "residuals")
combined_plot <- (wine_lm_res2 | wine_lm_res3) 
combined_plot + 
  plot_layout(guides = 'collect') + 
  plot_annotation(title = "Selected Residual Plot of Wine Quality MLR")
```


```{r Trasformed Model and Residuals, cache=TRUE}
## transformed model
wine_lm_interaction_tran <- lm(quality ~ alcohol + 
                                 log(sulphates) + log(residual.sugar) + 
                                 pH*color, data = wine_dat)
summary(wine_lm_interaction_tran)

## residual plots
create_res_plot(wine_lm_interaction_tran)

## confidence interval for coefficients
confint(wine_lm_interaction_tran)
confint(wine_lm_interaction_tran)*log(2) # un-transforming logged 
                                         # predictors to the origianl scale
```


## Model Comparison
```{r one-way ANOVA & AIC, cache=TRUE}
# nested transformation model
wine_lm_base_tran <- lm(quality ~ alcohol + log(sulphates) + 
                          log(residual.sugar) + pH, data = wine_dat)

summary(wine_lm_base_tran)

#model comparison with transformed model
anova(wine_lm_base_tran, wine_lm_interaction_tran)

## AIC's
AIC(wine_lm_interaction)
AIC(wine_lm_interaction_tran)
AIC(wine_lm_base_tran)
```


## Confidence Intervals 
```{r Linear Combination and CI, cache=TRUE}
# linear comb for white wine ph
wine_lm_interaction_tran$coefficients[5] -> redPH
wine_lm_interaction_tran$coefficients[7] -> whtPH_int

whtPH <- (redPH + whtPH_int)[[1]]

vcov(wine_lm_interaction_tran)[c(5, 7), c(5, 7)] -> ph_cov

# point estimate
ph_se <- sqrt(ph_cov[[1, 1]] + ph_cov[[2, 2]] + 2 * ph_cov[[1, 2]]) 

test_stat <- whtPH/ph_se # t-stat
2*pt(test_stat, df = 6497 - 7, lower.tail = F) # p-val

# confidence interval
wht_ci <- whtPH + c(-1, 1)*qt(0.975, df = 6497 - 7)*ph_se

# untransformed predictor
wine_lm_interaction_tran$coefficients[3] * log(2)
wine_lm_interaction_tran$coefficients[4] * log(2)
```


## Multicolinearity
```{r VIF, cache=TRUE}
#checking for VIF - must use base model, not interaction model
vif(wine_lm_base)
vif(lm(quality ~ alcohol + sulphates + residual.sugar + pH + color, 
       data = wine_dat)) # Might be this one; the base model doesn't have a color term
vif(lm(quality ~ alcohol + log(sulphates) + log(residual.sugar) + pH + color, 
       data = wine_dat)) # or the transformed one
```


## Influential Statistics
```{r Outliers with Summary Stats, cache=TRUE}
#figuring out outliers based on scatterplot matrix
mean_values <- wine_dat %>%
  summarize(across(c(alcohol, sulphates, pH, residual.sugar, citric.acid, fixed.acidity), 
                   mean, na.rm = TRUE))
mean_values

row_num <- 4381
case_values <- wine_dat[row_num, 
                        c("alcohol", "sulphates", "pH", "residual.sugar",
                          "citric.acid", "fixed.acidity")]
case_values
#This case has a very large residual sugar
```

```{r Cook Dist and Stud Res and Leverage, cache=TRUE}
# checking for influential observations
wine_dat_row <- wine_dat %>% mutate(case = row_number())
AUGwine_lm_interaction_tran <- augment(wine_lm_interaction_tran, 
                                  data = wine_dat_row)

# Cook's Distance
ggplot(data = AUGwine_lm_interaction_tran, aes(x = case, y = .cooksd)) + 
  geom_point() + 
  geom_point(data = AUGwine_lm_interaction_tran %>% 
               filter(case == 4381), color = "blue") + 
  geom_hline(yintercept=1, linetype="dashed", color = "red")  + 
  labs(y = "Cook's Distance", x = "Index") -> cookDistancePlot

# Studentized Residuals
ggplot(AUGwine_lm_interaction_tran, aes(x = case, y = .std.resid)) + geom_point() + 
  geom_point(data = AUGwine_lm_interaction_tran %>% 
               filter(case == 4381), color = "blue") + 
  geom_hline(yintercept=3, linetype="dashed", color = "red")  + 
  geom_hline(yintercept=-3, linetype="dashed", color = "red")  + 
  labs(y = "Studentized Residuals", x = "Index") -> studResiPlot

# Leverages
ggplot(AUGwine_lm_interaction_tran, aes(x = case, y = .hat)) + 
  geom_point() + 
  geom_point(data = AUGwine_lm_interaction_tran %>% 
               filter(case == 4381), color = "blue") + 
  geom_hline(yintercept=2*7/6497, linetype="dashed", color = "red")  + 
  labs(y = "Leverage", x = "Index") -> leveragePlot

cookDistancePlot|studResiPlot|leveragePlot # for report

# Selection of influential stats
high_L <- AUGwine_lm_interaction_tran %>% dplyr::select(case, .hat) %>% 
  arrange(desc(.hat)) %>%
  filter(.hat > 2*7/6497) # greater than twice the average
high_SR <- AUGwine_lm_interaction_tran %>% dplyr::select(case, .std.resid) %>% 
  arrange(desc(.std.resid)) %>% 
  filter(.std.resid > 3) # greater than 3 se's
high_CD <- AUGwine_lm_interaction_tran %>% dplyr::select(case, .cooksd) %>% 
  arrange(desc(.cooksd)) %>% 
  filter(.cooksd > 1) # greater than 1

# List of influential stats
high_L
high_SR
high_CD
```

```{r (Not) Removing Outliers, cache=TRUE}
## Reg on no outlier
wine_dat_no_outliers <- wine_dat %>%
  filter(residual.sugar != 65.8)
winenooutlierslm <- lm(quality ~ alcohol + sulphates + residual.sugar + pH*color, 
                       data = wine_dat_no_outliers)
summary(winenooutlierslm) #doesn't change conclusion

# visuals of (not) removing the outlier
create_inf_plot <- function(var_name) {
  ggplot(data = wine_dat, 
         aes_string(x = var_name, y = "quality")) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE, color = "blue") +
    geom_point(data = wine_dat %>% filter(residual.sugar == 65.8), 
               color = "red") +
    geom_smooth(data = wine_dat %>% filter(residual.sugar == 65.8), 
                method = "lm", se = FALSE, color = "red") +
    labs(title = paste("Plot of Quality vs", var_name))
}

plot_list2 <- map(variable_names, create_inf_plot)
plot_grid2 <- wrap_plots(plot_list2, ncol = 2)
plot_grid2
```


## Sequential Selection
```{r Backward and Forward Selection, cache=TRUE, results='hide', message=FALSE, warning=FALSE}
set.seed(67393937)

upper_model <- lm(quality ~ (pH + alcohol + log(residual.sugar) + color + log(sulphates) + 
                               fixed.acidity + volatile.acidity + citric.acid + chlorides + 
                               free.sulfur.dioxide + total.sulfur.dioxide + density)^2,
                 data = wine_dat)
lower_model <- lm(quality ~ 1, data = wine_dat)

#backward selection
backwardSelectModel <- stepAIC(upper_model, scope = list(lower = lower_model, 
                                                         upper = upper_model),
                               direction = "backward")
summary(backwardSelectModel)

#forward selection
forwardSelectModel <- stepAIC(lower_model, scope = list(lower = lower_model, 
                                                         upper = upper_model),
                               direction = "forward")
summary(forwardSelectModel)

anova(wine_lm_interaction_tran, backwardSelectModel)
anova(wine_lm_interaction_tran, forwardSelectModel)
```